### ISSUE TITLE
IndexError: invalid index to scalar variable

### ISSUE THREAD

**Issue by clemenhua** [hpc203/Yolo-Fastest-opencv-dnn#2]
```
Traceback (most recent call last):
  File "D:/yolo/Yolo-Fastest-opencv-dnn-master/main_yolov3.py", line 103, in <module>
    outs = net.forward(getOutputsNames(net))
  File "D:/yolo/Yolo-Fastest-opencv-dnn-master/main_yolov3.py", line 27, in getOutputsNames
    return [layersNames[i[0] - 1] for i in net.getUnconnectedOutLayers()]
  File "D:/yolo/Yolo-Fastest-opencv-dnn-master/main_yolov3.py", line 27, in <listcomp>
    return [layersNames[i[0] - 1] for i in net.getUnconnectedOutLayers()]
IndexError: invalid index to scalar variable.

进程已结束，退出代码为 1

```
这个是什么原因呢请问，没怎么搞懂

**Comment by TTxxtt** [comment]
main_yolov3.py，会出现报错，把41行i[0],改成i,115行i[0],改成i，即可。

**Comment by clemenhua** [comment]
您好，您的来信我已经收到，将尽快给您回复，谢谢！Thank you for your mail,I will give prompt attention and response to your mail ASAP.
